disabled_rules:
    - variable_name
    - force_cast 
enabled_rules:
    - trailing_newline
    - opening_brace
    - empty_count
    - comma
    - colon
    - type_name
    - variable_name_min_length
    - trailing_semicolon
    - force_try
    - function_body_length
    - nesting
    - conditional_binding_cascade
    - variable_name_max_length
    - operator_whitespace
    - control_statement
    - legacy_constant
    - line_length
    - return_arrow_whitespace
    - trailing_whitespace
    - closing_brace
    - statement_position
    - type_body_length
    - todo
    - legacy_constructor
    - valid_docs
    - missing_docs
    - file_length
    - leading_whitespace
    - empty_count
excluded:
    - Pods
line_length: 
    - 120
    - 150
type_body_length: 
    - 500 
    - 600
function_body_length: 
    - 100 
    - 150
file_length:
    - 500
    - 600
